name: Build 1.0

on:
  push:
    branches: [ develop ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          npm ci --prefix processing 
          node processing
          npm ci --prefix site
          npm run deploy --prefix site

      - name: Generate App List # Have to run it again because the deploy wipes the file and folders out
        run: |
          npm ci --prefix processing
          node processing

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          force: false
          clean: false
